name: on-push
on:
  push:
    branches:
      - "main"
jobs:
  run-todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          run_install: |
            - args: [--frozen-lockfile]
      - run: pnpm build
      - run: pnpm todos
      - uses: EndBug/add-and-commit@v7
        with:
          add: "langs/*/README.md"
          message: "bot: update language todos"
